networks:
  cerebro_net:
    driver: bridge

services:

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - cerebro_net

  backend:
    build:
      context: ./backend
    restart: always
    networks:
      - cerebro_net
    ports:
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cerebro_fetcher/morpheus-sql-database-885f6d117879.json
    volumes:
      - ./backend/cerebro_fetcher/morpheus-sql-database-885f6d117879.json:/app/cerebro_fetcher/morpheus-sql-database-885f6d117879.json:ro
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./backend
    restart: always
    networks:
      - cerebro_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cerebro_fetcher/morpheus-sql-database-885f6d117879.json
    volumes:
      - ./backend/cerebro_fetcher/morpheus-sql-database-885f6d117879.json:/app/cerebro_fetcher/morpheus-sql-database-885f6d117879.json:ro
    depends_on:
      - redis
      - backend
    command: celery -A celery_worker worker --loglevel=info --pool=solo

  celery_beat:
    build:
      context: ./backend
    restart: always
    networks:
      - cerebro_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cerebro_fetcher/morpheus-sql-database-885f6d117879.json
    volumes:
      - ./backend/cerebro_fetcher/morpheus-sql-database-885f6d117879.json:/app/cerebro_fetcher/morpheus-sql-database-885f6d117879.json:ro
      - celerybeat_data:/app/celerybeat
    depends_on:
      - redis
      - backend
    command: celery -A celery_worker beat --loglevel=info --schedule=/app/celerybeat/celerybeat-schedule

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://cerebro.afgmedia.co.uk
    restart: always
    networks:
      - cerebro_net
    ports:
      - "3008:3000"
    depends_on:
      - backend

volumes:
  celerybeat_data:
